### ISSUE TITLE
Thera Connect dont work

### ISSUE THREAD

**Issue by CuloArdido** [ErikKalkoken/theraconnect-issues#1]
Do you still maintain this project? Because I found [Thera Connect](http://www.kalkoken.org/apps/theraconnect/) while I was researching about Thera, but when I wanted to enter, only a blank page appeared and the main domain (www.kalkoken.org) now seemed to belong to one Mark Phillips.
I also noticed that you haven't posted anything in [your blog](http://kalkoken.altervista.org/blog/) for a year.
In case you dont can/want keep this online at least you should consider releasing the source code of the server so that others can have this tool available.

**Comment by ErikKalkoken** [comment]
Yeah, I still maintain Thera Connect. My provider has currently some availability issues with leads to down times during backup runs every night (UTC 02 - 04). But outside that time the site is up an running, as are all my other sides.
The "Mark Philips" website is just the demo page. I should properly remove that ;-) And its true, I have not written a blog entry for some time now. But other than that everything is still fully maintained.
